apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: NodePort
  selector:
    app: gitlab-app
  ports:
  - name: 80-80
    port: 80
    nodePort: 30082
    targetPort: 80
    name: http