apiVersion: v1
kind: Service
metadata:
  name: gl-svc
spec:
  ports:
  - name: 80-7777
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 7777
  selector:
    app: gl-app
  type: NodePort
  