apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-app
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gl-app
  template:
    metadata:
      labels:
        app: gl-app
    spec:
      containers:
      - image: gitlab/gitlab-ce
        name: gl-app
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: "external_url 'http://gitlab-service.default/';gitlab_rails['registry_enabled'] = true;gitlab_rails['registry_api_url'] = \"http://172.17.0.2:5000\""
        ports:
        - containerPort: 80
          name: HTTP
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: data
      volumes:
        - name: data
          emptyDir: {}
