# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  etc_Hosts = ""
  private_ip = "192.168.56.110"

  config.vm.box = "debian/bullseye64"
  
  config.trigger.before :up, :reload do |trigger|
    trigger.info = 'Vagrant up called, we will execute the configuration script for virtual box and check if the network configuration is already done or not.'
    trigger.run = {inline: 'sudo ./scripts/config_host.sh'}
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "chbadadS"
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.hostname = "chbadadS"
  config.vm.network "private_network", ip: private_ip
  config.vm.network "forwarded_port", guest:6443, host:6443
  config.vm.network "forwarded_port", guest:8080, host:8080
  config.vm.provision :shell, path: "./scripts/config_k3s.sh"

  # config.vm.synced_folder "../data", "/vagrant_data"

    
end # fin de la bouble principale
