# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  private_ip = "192.168.56.110"
  config.vm.box = "debian/bullseye64"
  config.vm.provider "virtualbox" do |v|
    v.name = "chbadadS"
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.hostname = "chbadadS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest:6443, host:6443
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.provision :shell, path: "./scripts/config_k3s.sh"

  config.vm.synced_folder "./controllers", "/controllers"

    
end # fin de la bouble principale
